# -*- coding: utf-8 -*-
"""Another copy of Day3_RPG_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbmFxpqK1PFepgPUWQtJTlHyXmj_tU83

# ⚔️ Day 3 — Deploy Your Boss Battle RPG!

### Take the game you built in your terminal and put it on the web.

Today has two halves:

| Part | What you do |
|------|-------------|
| **Part 1 — Convert** | Rewrite your Day 2 class so a web page can display it |
| **Part 2 — Deploy** | Drop it into the app, launch it, share the link |

---

### 🗺️ Road map

1. **Read "What changes and why"** below — it's four small edits, but one of them is sneaky
2. **Convert your class in the Scratch Pad**, then run the **Conversion Test**
3. Only once the test passes: **run Cell 1** to install Streamlit
4. **Paste your converted class into Cell 2** at `TODO 1`
5. **Uncomment TODOs 2, 3, 4** — three lines to put your class in the UI
6. **Run Cells 2 → 3 → 4** to launch and share your game
7. **Tackle the bonus challenges** to make it your own

> ⚠️ **Convert and test BEFORE you deploy.** A broken class inside a running web app is miserable
> to debug — the error hides in a server log instead of appearing under your cell.

> **Re-deploying after edits:** edit Cell 2, then re-run Cell 2 → Cell 3 → Cell 4.

---
# Part 1 — Convert Your Day 2 Code

## Why anything has to change at all

On Day 1 and Day 2 your game talked to you through `print()`. That worked because you and the code
were in the same place — the terminal.

A web page is somewhere else entirely. Your code runs on a server; the player is in a browser.
When the server calls `print()`, the text lands in a log file the player will never see.

So instead of *printing* a message, your methods now **hand the message back** and let the web app
decide where to put it:

```python
# Day 1 / Day 2 — shout into the room
print(f"{self.name} attacks for {damage} damage!")

# Day 3 — hand the message back
return f"{self.name} attacks for **{damage}** damage!"
```

Same sentence. Different destination.

*(The `**stars**` make text bold on the web page — markdown, same as these notebook cells.)*

---

## The four edits

| # | Change | Why |
|---|---|---|
| 1 | `print(...)` → `return f"..."` | The web page needs the text, not the terminal |
| 2 | `damage = self.crit_check(d)` → `damage, crit = self.crit_check(d)` | `crit_check` can't print any more either, so it now returns **two** things: the damage *and* whether it was a crit |
| 3 | Add `CLASS_NAME` and `EMOJI` at the top of your class | The dropdown and the health bars read these |
| 4 | `other.health -= damage` → `other.health = max(0, other.health - damage)` | Health bars break on negative numbers. `max(0, …)` floors it at zero |

Edit 2 in full:

```python
# Day 2 — crit_check printed "Critical Hit!" itself and returned one number
damage = self.crit_check(damage)

# Day 3 — it returns a PAIR, so you unpack it and write the message yourself
damage, crit = self.crit_check(damage)
msg = f"⚔️ {self.name} uses Heavy Slash for **{damage}** damage!"
return msg + " 🔥 *Critical hit!*" if crit else msg
```

If you forget to unpack, `damage` becomes the tuple `(24, False)` and the next line throws
`TypeError: unsupported operand type(s) for -: 'int' and 'tuple'`. Loud and easy to spot — good.

---
## ⚠️ The sneaky one — `return` ends the method

This catches nearly everybody, and it only bites people whose move prints **more than once**.

`print()` can happen as many times as you like. `return` happens **once, and then the method stops
immediately.** Every line after it is dead.

```python
# ❌ BROKEN — only the first line ever runs
def special_attack(self, other):
    return f"{self.name} focuses..."
    return f"...and strikes for {damage}!"   # never happens
```

### The fix: build the message in a variable, return it at the end

```python
# ✅ WORKS
def special_attack(self, other):
    msg = f"{self.name} focuses..."          # start the message
    msg += f"\n\n...and strikes for **{damage}**!"   # add to it
    return msg                                # hand it over, once
```

`+=` on a string means "stick this on the end". `\n\n` makes a new paragraph on the web page.

### And a bonus trick: the guard clause

When a whole method is wrapped in `if self.mana >= 30:`, converting to returns lets you flip it
around and get rid of a whole level of indentation:

```python
# Day 2 shape                        # Day 3 shape
if self.mana >= 30:                  if self.mana < 30:
    ...everything...                     return "❌ Not enough mana!"
else:                                ...everything, one indent shallower...
    print("Not enough mana!")
```

Bail out early on the failure case, then write the success case flat. Same logic, easier to read.

---
## 🔧 Scratch Pad — convert your class here

These next two cells are a **before and after**.

| Cell | What's in it |
|---|---|
| **BEFORE** | Your Day 2 code, **entirely commented out**. Nothing runs — it's there to read |
| **AFTER** | The same code converted for the web. This one actually runs |

Read them side by side. Every difference between them is one of the four edits.

Both are **plain Python** — no Streamlit, no web server. Convert here first, because errors show up
right under the cell where you can read them.

The AFTER cell gives you:
- `Character` — the base class, converted for you
- `Warrior` and `Mage` — the easy conversion, one print per branch
- `Monk` — the hard conversion, seven prints in one method
- `Boss` — your Day 2 AI, converted
- **an empty slot for your own class**

**Delete the examples you don't need** and paste yours in their place.
"""

# =============================================================================
#  BEFORE — YOUR DAY 2 CODE
#  Every line here is commented out. Nothing in this cell runs.
#  It is here so you can compare it, line by line, with the cell below.
# =============================================================================

# import random
#
# class Character:
#     def __init__(self, name):
#         self.name       = name
#         self.health     = 100
#         self.max_health = 100
#         self.mana       = 50
#         self.max_mana   = 50
#
#     def is_alive(self):
#         return self.health > 0
#
#     def status(self):                                     # ← GONE in Day 3.
#         print(f"{self.name} HP: {self.health}/{self.max_health}")   # the health
#                                                           #   bars replace it
#     def crit_check(self, damage):
#         if random.random() < 0.2:
#             print("🔥 Critical Hit!")          # ← can't print any more, so...
#             return damage * 2                  # ← ...it returns TWO things now
#         return damage
#
#     def basic_attack(self, other):
#         damage = self.crit_check(random.randint(5, 10))    # ← needs unpacking
#         other.health -= damage                             # ← needs max(0, …)
#         print(f"{self.name} punches {other.name} for {damage} damage!")  # ← return
#
#     def heal(self):
#         if self.mana >= 10:
#             amount      = random.randint(15, 25)
#             self.mana  -= 10
#             self.health = min(self.health + amount, self.max_health)
#             print(f"{self.name} heals for {amount} HP!")    # ← return
#         else:
#             print(f"{self.name} doesn't have enough mana to heal.")   # ← return
#
#     def meditate(self):
#         regen     = random.randint(10, 20)
#         self.mana = min(self.mana + regen, self.max_mana)
#         print(f"{self.name} meditates and restores {regen} mana.")    # ← return
#
#
# class Warrior(Character):
#     CLASS_NAME = "Warrior"                     # ← keep. Day 3 also wants EMOJI
#
#     def special_attack(self, other):
#         if self.mana >= 10:
#             damage = random.randint(20, 30)
#             damage = self.crit_check(damage)   # ← damage, crit = …
#             self.mana -= 10
#             other.health -= damage             # ← max(0, …)
#             print(f"{self.name} uses ⚔️  Heavy Slash for {damage} damage!")  # ← return
#         else:
#             print("Not enough mana for Heavy Slash.")                       # ← return
#
#
# class Mage(Character):
#     CLASS_NAME = "Mage"
#
#     def special_attack(self, other):
#         if self.mana >= 15:
#             damage = random.randint(25, 35)
#             damage = self.crit_check(damage)
#             self.mana -= 15
#             other.health -= damage
#             print(f"{self.name} casts 🔥 Fireball for {damage} damage!")
#         else:
#             print("Not enough mana for Fireball.")
#
#
# class Boss(Character):
#     def __init__(self):
#         super().__init__("Doom Bringer")       # ← unchanged. __init__ never printed
#         self.health     = 150
#         self.max_health = 150
#         self.mana       = 40
#         self.max_mana   = 40
#
#     def special_move(self, target):
#         if self.mana >= 20:
#             print("💢 Doom Bringer unleashes *Desolation Wave*!")   # ← TWO prints
#             damage = random.randint(40, 50)                        #   in one
#             damage = self.crit_check(damage)                       #   method!
#             self.mana    -= 20
#             target.health -= damage
#             print(f"💀 {target.name} is hit for {damage} massive damage!")
#         else:
#             self.basic_attack(target)          # ← becomes  return self.basic_attack(…)
#
#     def choose_ai_action(self, target):
#         options = []
#         if self.health < 60 and self.mana >= 10:
#             options.append(("heal", 40 + (60 - self.health)))
#         if self.mana < 10:
#             options.append(("meditate", 30 - self.mana))
#         if self.mana >= 20:
#             options.append(("special", 10 + (100 - target.health)))
#         options.append(("basic", 5 + random.randint(0, 5)))
#
#         best = max(options, key=lambda x: x[1])[0]    # ← the AI logic itself
#                                                       #   does NOT change at all
#         if best == "heal":
#             self.heal()                               # ← return self.heal()
#         elif best == "meditate":
#             self.meditate()                           # ← return self.meditate()
#         elif best == "special":
#             self.special_move(target)                 # ← return self.special_move(…)
#         else:
#             self.basic_attack(target)                 # ← return self.basic_attack(…)

# =============================================================================
#  Notice what did NOT change:
#    • __init__          — it never printed anything
#    • is_alive()        — it already returned a value
#    • the AI scoring    — options, append, max(key=…) are untouched
#    • every number      — damage ranges, mana costs, thresholds, all identical
#
#  Only the OUTPUT changed. The game is the same game.
# =============================================================================
print("📖 Reference cell — nothing here runs. Now look at the cell below.")

"""### AFTER — the Day 3 version

Same classes, same numbers, same logic. Run this one.

As you read, find each of the four edits in the code:
`return` instead of `print` · `damage, crit =` unpacking · `CLASS_NAME` and `EMOJI` ·
`max(0, …)` on health.

"""

import random

# =============================================================================
#  AFTER — THE DAY 3 VERSION
#  Compare every method to its commented twin in the cell above.
# =============================================================================

class Character:
    def __init__(self, name):
        self.name       = name
        self.health     = 100
        self.max_health = 100
        self.mana       = 50
        self.max_mana   = 50

    def is_alive(self):
        return self.health > 0

    def crit_check(self, damage):
        if random.random() < 0.2:
            return damage * 2, True
        return damage, False

    def basic_attack(self, other):
        damage, crit = self.crit_check(random.randint(5, 10))
        other.health = max(0, other.health - damage)
        msg = f"{self.name} punches {other.name} for **{damage}** damage!"
        return msg + " 🔥 *Critical hit!*" if crit else msg

    def heal(self):
        if self.mana >= 10:
            amount      = random.randint(15, 25)
            self.mana  -= 10
            self.health = min(self.health + amount, self.max_health)
            return f"💚 {self.name} heals for **{amount}** HP!"
        return f"❌ {self.name} doesn't have enough mana to heal!"

    def meditate(self):
        regen     = random.randint(10, 20)
        self.mana = min(self.mana + regen, self.max_mana)
        return f"✨ {self.name} meditates and restores **{regen}** mana."


# ── Warrior — the reference conversion ───────────────────────────────────────
class Warrior(Character):
    CLASS_NAME = "Warrior"
    EMOJI      = "⚔️"

    def special_attack(self, other):
        if self.mana >= 10:
            damage, crit = self.crit_check(random.randint(20, 30))
            self.mana   -= 10
            other.health = max(0, other.health - damage)
            msg = f"⚔️ {self.name} uses **Heavy Slash** for **{damage}** damage!"
            return msg + " 🔥 *Critical hit!*" if crit else msg
        return f"❌ {self.name} doesn't have enough mana for Heavy Slash!"


# ── Mage — the EASY conversion: one print per branch → one return per branch ─
class Mage(Character):
    CLASS_NAME = "Mage"
    EMOJI      = "🔮"

    def special_attack(self, other):
        if self.mana >= 15:
            damage, crit = self.crit_check(random.randint(25, 35))
            self.mana   -= 15
            other.health = max(0, other.health - damage)
            msg = f"🔮 {self.name} casts **Fireball** for **{damage}** damage!"
            return msg + " 🔥 *Critical hit!*" if crit else msg
        return f"❌ {self.name} doesn't have enough mana for Fireball!"


# ── Monk — the HARD conversion: SEVEN prints in one method ──────────────────
#     You cannot swap each print for a return — the first one ends the method.
#     Instead: flavour goes in a VARIABLE, add with +=, return ONCE at the end.
#     Also note the guard clause on line 1 — it removes a level of indentation.
class Monk(Character):
    CLASS_NAME = "Monk"
    EMOJI      = "🧘"

    def __init__(self, name):
        super().__init__(name)
        self.hit = False

    def special_attack(self, other):
        if self.mana < 30:
            return f"❌ {self.name} doesn't have enough mana for a great hit!"

        self.mana -= 30

        if self.hit:
            damage, crit = self.crit_check(random.randint(25, 50))
            other.health = max(0, other.health - damage)
            msg = f"🧘 Monk {self.name} uses a large attack for **{damage}** damage!"
            return msg + " 🔥 *Critical hit!*" if crit else msg

        self.hit = True
        roll = random.randint(0, 100)

        if   roll == 0:   flavour = "Monk misses!"
        elif roll <  10:  flavour = "Monk's focus is off! Low damage!"
        elif roll <  20:  flavour = "Monk is a bit off on the hit. Close to a miss!"
        elif roll <  70:  flavour = "Monk does good damage, focus is good!"
        elif roll <  90:  flavour = "Monk's focus is perfect! Deals good damage."
        elif roll < 100:  flavour = "Monk does a heavy hit! Aim is to be the best!"
        else:             flavour = "WOW! Monk does a PERFECT hit!!! Most damage done!"

        msg = f"🧘 {self.name} the Monk focuses! Ready to hit!\n\n*{flavour}*"

        if roll > 0:
            damage, crit = self.crit_check(roll)
            other.health = max(0, other.health - damage)
            msg += f"\n\nThe Monk strikes {other.name} for **{damage}** damage!"
            if crit:
                msg += " 🔥 *Critical hit!*"

        return msg


# ── Boss — your Day 2 AI, converted (given) ─────────────────────────────────
class Boss(Character):
    CLASS_NAME = "Boss"
    EMOJI      = "👹"

    def __init__(self):
        super().__init__("Doom Bringer")
        self.health = self.max_health = 150
        self.mana   = self.max_mana   = 40

    def special_move(self, target):
        if self.mana < 20:
            return self.basic_attack(target)

        damage, crit = self.crit_check(random.randint(40, 50))
        self.mana    -= 20
        target.health = max(0, target.health - damage)

        msg  = "💢 Doom Bringer unleashes **Desolation Wave**!"
        msg += f"\n\n💀 {target.name} is hit for **{damage}** massive damage!"
        if crit:
            msg += " 🔥 *Critical hit!*"
        return msg

    def choose_ai_action(self, target):
        options = []
        if self.health < 60 and self.mana >= 10:
            options.append(("heal",     40 + (60 - self.health)))
        if self.mana < 10:
            options.append(("meditate", 30 - self.mana))
        if self.mana >= 20:
            options.append(("special",  10 + (100 - target.health)))
        options.append(("basic",         5 + random.randint(0, 5)))

        best = max(options, key=lambda x: x[1])[0]

        if best == "heal":     return self.heal()
        if best == "meditate": return self.meditate()
        if best == "special":  return self.special_move(target)
        return self.basic_attack(target)


# =============================================================================
#  👇 YOUR CLASS GOES HERE — paste your Day 2 class and convert it
# =============================================================================

class Ninja(Character):
     CLASS_NAME = "Ninja"
     EMOJI      = "🔪" # Added EMOJI

     def special_attack(self, other):
         if self.mana >= 20:
             base_damage = random.randint(25, 35)
             damage, crit = self.crit_check(base_damage) # Unpacked crit_check result
             self.mana -= 20
             other.health = max(0, other.health - damage) # Applied max(0, ...) for health
             msg = f"🔪 {self.name} casts **throwing knife** for **{damage}** damage!"
             return msg + " 🔥 *Critical hit!*" if crit else msg
         return f"❌ {self.name} doesn't have enough mana for throwing knife!" # Added '!' for consistency


print("✅ Classes defined. Now run the Conversion Test cell below.")

"""### 🧪 Conversion Test — run this before you deploy

Change `TEST_CLASS` below to your class, then run it. It checks the four edits one at a time and
tells you exactly which one is missing.

**Get all checks passing here.** Every one of these failures is invisible inside Streamlit — the
app just shows a blank log line or crashes with a stack trace buried in a server file.

"""

# =============================================================================
#  CONVERSION TEST — plain Python, no web server
# =============================================================================
TEST_CLASS = Ninja          # ← change to YOUR class (no quotes, no brackets)

problems = []

def check(label, ok, hint):
    print(f"{'✅' if ok else '❌'}  {label}")
    if not ok:
        problems.append(hint)

print(f"Testing {TEST_CLASS.__name__}\n" + "-" * 52)

# Edit 3 — the UI attributes
check("Has CLASS_NAME", hasattr(TEST_CLASS, "CLASS_NAME"),
      "Add  CLASS_NAME = \"YourName\"  just under the class line.")
check("Has EMOJI", hasattr(TEST_CLASS, "EMOJI"),
      "Add  EMOJI = \"🔮\"  just under the class line.")

hero  = TEST_CLASS("Testy")
dummy = Character("Dummy")
dummy.health = dummy.max_health = 400

# Edit 1 — returns instead of prints
hero.mana = hero.max_mana
result = hero.special_attack(dummy)
check("special_attack RETURNS something", result is not None,
      "Your method still uses print(). Change print(f\"...\") to return f\"...\".")
check("...and it returns TEXT", isinstance(result, str),
      "Return an f-string, not a number or a tuple.")

# Edit 2 / 4 — the attack actually landed, health floored at 0
check("The target actually lost health", dummy.health < 400,
      "Either  other.health = max(0, other.health - damage)  is missing, or "
      "your move costs more mana than you start with (50).")
dummy.health = 5
hero.mana = hero.max_mana
hero.special_attack(dummy)
check("Health never goes negative", dummy.health >= 0,
      "Wrap it: other.health = max(0, other.health - damage)")

# The move still costs SOMETHING — mana for most classes, HP for a few.
# (Top both bars up first: some moves cost a lot.)
hero.mana   = hero.max_mana
hero.health = hero.max_health
mana_before, hp_before = hero.mana, hero.health
hero.special_attack(dummy)
check("Special attack costs something (mana or HP)",
      hero.mana < mana_before or hero.health < hp_before,
      "Your  self.mana -= COST  (or self.health -= COST) line is missing, "
      "or the cost is higher than you can ever afford.")

# The failure branch must return text too
hero.mana = 0
broke = hero.special_attack(dummy)
check("No-mana branch returns text too", isinstance(broke, str),
      "The else / not-enough-mana branch still prints instead of returning.")

print("-" * 52)
if problems:
    print("⚠️  Fix these before deploying:\n")
    for p in problems:
        print("   •", p)
else:
    print("🎉 All checks passed — your class is ready for the web app.")
    print("   Copy it into Cell 2 at TODO 1.")

# =============================================================================
#  BONUS CHECK — watch a whole fight in plain text
#  Every line below came back as a RETURN VALUE. On the web page these same
#  strings go into the battle log instead of the screen.
# =============================================================================
hero = TEST_CLASS("Hero")
boss = Boss()
turn = 0

while hero.is_alive() and boss.is_alive() and turn < 40:
    turn += 1
    # a simple player: heal when hurt, special when affordable, else meditate
    if hero.health < 40 and hero.mana >= 10:
        line = hero.heal()
    else:
        line = hero.special_attack(boss)
        if line.startswith("❌"):          # couldn't afford it — punch instead
            line = hero.basic_attack(boss)
    print(f"T{turn}  {line}")

    if not boss.is_alive():
        print(f"\n🏆 {hero.name} wins in {turn} turns!")
        break

    print(f"T{turn}  {boss.choose_ai_action(hero)}")

    if not hero.is_alive():
        print(f"\n💀 {boss.name} wins in {turn} turns.")
        break
else:
    print("\n⏱️  Stalemate after 40 turns — nobody could finish it.")

"""---
# Part 2 — Deploy

Your class is converted and tested. Now it goes into the real app.

**What you're about to copy:** just your class — from `class YourName(Character):` down to its last
line. Not the `Character` base class (Cell 2 already has it), not the test cell.

**Where it goes:** Cell 2, at the line marked `YOUR CLASS GOES BELOW THIS LINE`.

Then three one-line TODOs (2, 3, 4) put it in the dropdown, give it a description card, and build it
when the player hits Start.

> If you added extra moves on Day 2 — a `focus()`, a `reckless_swing()` — they'll come across with
> your class, but there's no button for them yet. Bonus challenge 2 shows how to add one.

---
## ⚡ Streamlit Cheat Sheet — keep this open in a second tab

Everything below already appears somewhere in Cell 2. You don't have to write Streamlit from
scratch today — but you do have to **read** it, and you'll need it for the bonus challenges.

---

### 🧠 The one idea that's different from every program you've written

**Streamlit re-runs your whole script, top to bottom, every single time the player clicks anything.**

Not the one function. The whole file. That's how the page redraws itself.

Which means a normal variable is useless — it gets rebuilt from scratch on every click:

```python
turn = 0          # ❌ back to 0 after every button press
turn += 1
```

Anything that must survive a click goes in **`st.session_state`** — a dictionary Streamlit keeps
between re-runs:

```python
st.session_state["turn"] = 0        # ✅ survives
st.session_state["turn"] += 1
```

In Cell 2 there's a shortcut near the top — `state = st.session_state` — so the rest of the code
just writes `state["turn"]`, `state["player"]`, `state["log"]`.

**This is also why `st.rerun()` exists.** After you change something, you ask Streamlit to redraw
the page immediately instead of waiting.

---

### 📓 Notebook commands (the lines starting with `!` or `%%`)

| Command | What it does |
|---|---|
| `!pip install streamlit -q` | `!` runs a **terminal** command, not Python. `-q` = quiet |
| `%%writefile app.py` | Saves the rest of the cell into a file. **Nothing runs** — you'll only see `Writing app.py` |
| `!npx localtunnel --port 8501` | Opens the public link. **Blocks on purpose** — the spinner means it's working |

---

### ✍️ Text and layout

| Function | What it does |
|---|---|
| `st.title("⚔️ Boss Battle")` | Biggest heading |
| `st.subheader("Choose your hero")` | Smaller heading |
| `st.caption("❤️ HP 80 / 100")` | Small grey text |
| `st.markdown("**bold** and *italic*")` | Any markdown — this is how your battle log renders |
| `st.divider()` | A horizontal line |
| `st.columns(2)` | Splits the page into side-by-side columns |

Columns are used with `with`:

```python
left, right = st.columns(2)
with left:
    st.title("You")
with right:
    st.title("Boss")
```

`st.columns([5, 1, 5])` gives **widths** instead of a count — that's the wide/narrow/wide layout
around the ⚡ in the battle screen.

---

### 🎛️ Things the player interacts with

| Function | Returns |
|---|---|
| `st.text_input("Hero name")` | Whatever they typed, as a string |
| `st.selectbox("Class", ["Warrior ⚔️"])` | The option they picked, as a string |
| `st.button("Attack")` | `True` **only** on the click that pressed it, `False` every other re-run |

That button behaviour is why the code looks like this:

```python
if st.button("⚔️ Basic Attack"):
    action = "basic"
```

Useful button options:

| Option | Effect |
|---|---|
| `type="primary"` | Makes it the bright, obvious button |
| `use_container_width=True` | Stretches it to fill its column |
| `disabled=(count == 0)` | Greys it out — how the potion button locks at zero |
| `key="item_potion"` | A unique id. **Required** when you make buttons inside a loop |

---

### 📊 Boxes, bars and scroll areas

| Function | What it does |
|---|---|
| `st.info("...")` | Blue box — the class description cards |
| `st.success("...")` | Green box — victory screen |
| `st.error("...")` | Red box — defeat screen |
| `st.warning("...")` | Yellow box — "please enter a hero name!" |
| `st.progress(0.8)` | A bar. **Needs 0.0–1.0**, so health bars pass `health / max_health` |
| `st.container(height=220)` | A fixed-height scrolling box — the battle log |
| `st.balloons()` | 🎈 |
| `st.set_page_config(page_title=..., page_icon=...)` | The browser tab's title and icon. Must be the **first** Streamlit call in the file |
| `st.audio("song.mp3")` | Plays audio — bonus challenge 7 |

⚠️ `st.progress()` crashes on a value above 1.0 or below 0. That's the real reason for
`max(0, other.health - damage)` — a negative health bar is an error, not just ugly.

---

### 🔁 The commands you'll type most today

| Situation | Do this |
|---|---|
| Changed your game code | Re-run **Cell 2 → Cell 3 → Cell 4**, in that order |
| Link asks for a password | Paste the IP printed by Cell 3 |
| Page is blank or broken | Read the server log — it's not in the cell output |

```python
# paste in a new cell to see the real error
print(open('/content/streamlit.log').read()[-2000:])
```

---

### 🔍 Quick lookup — "I want to..."

| I want to... | Use |
|---|---|
| show a message in the battle log | `log("your **message**")` |
| add a new button | `if st.button("Label"): action = "yourthing"` |
| show a number that changes | `st.caption(f"Potions: {state['potions']}")` |
| remember something between clicks | `state["thing"] = value` |
| redraw the page right now | `st.rerun()` |
| put two things side by side | `a, b = st.columns(2)` then `with a:` |

## Cell 1 — Install Streamlit
"""

!pip install streamlit -q
print('✅ Streamlit installed!')

"""## Cell 2 — Your Game Code

This writes everything below `%%writefile app.py` into a file called `app.py`.

**Your tasks:**
- 👇 Find **TODO 1** — paste your Day 1 class and make the 3 small changes described
- 👇 Find **TODOs 2, 3, 4** — uncomment 3 lines to add your class to the UI

Everything else is already working — you don't need to touch the Streamlit UI code below the TODO sections.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# 
# st.set_page_config(page_title="Nate's GAME!", page_icon="⚔️", layout="centered")
# 
# # =============================================================================
# # PART 1 — GAME CLASSES
# # =============================================================================
# #
# # ✏️  ONE SMALL CHANGE from your Day 1 / Day 2 code
# # ─────────────────────────────────────────────────
# # Your terminal game used print() to show messages.
# # Streamlit can't read terminal output — it needs the message as a return value.
# #
# #   OLD (Day 1):  print(f"{self.name} attacks for {damage} damage!")
# #   NEW (Day 3):  return f"{self.name} attacks for **{damage}** damage!"
# #
# # That's the only change needed!  Everything else stays the same.
# #
# # Also update crit_check calls:
# #   OLD:  damage = self.crit_check(damage)          → single return value
# #   NEW:  damage, crit = self.crit_check(damage)    → now returns (damage, bool)
# #
# # =============================================================================
# 
# # ── Base Character Class  (given — no changes needed) ─────────────────────────
# 
# class Character:
#     def __init__(self, name):
#         self.name       = name
#         self.health     = 100
#         self.mana       = 50
#         self.max_health = 100
#         self.max_mana   = 50
# 
#     def is_alive(self):
#         return self.health > 0
# 
#     def crit_check(self, damage):
#         """Returns (damage, is_crit) tuple — no print, just values."""
#         if random.random() < 0.2:
#             return damage * 2, True
#         return damage, False
# 
#     def basic_attack(self, other):
#         damage, crit = self.crit_check(random.randint(5, 10))
#         other.health  = max(0, other.health - damage)
#         msg = f"{self.name} punches {other.name} for **{damage}** damage!"
#         return msg + " 🔥 *Critical hit!*" if crit else msg
# 
#     def heal(self):
#         if self.mana >= 10:
#             amount      = random.randint(15, 25)
#             self.mana  -= 10
#             self.health = min(self.health + amount, self.max_health)
#             return f"💚 {self.name} heals for **{amount}** HP!"
#         return f"❌ {self.name} doesn't have enough mana to heal!"
# 
#     def meditate(self):
#         regen     = random.randint(10, 20)
#         self.mana = min(self.mana + regen, self.max_mana)
#         return f"✨ {self.name} meditates and restores **{regen}** mana."
# 
# 
# # ── Warrior  (given — already adapted as an example) ─────────────────────────
# #
# #   Changes made from Day 1:
# #     ✅ Added  CLASS_NAME  and  EMOJI  class attributes (needed for the UI)
# #     ✅ Changed  print(...)  →  return f"..."
# #     ✅ Updated  crit_check  to unpack  (damage, crit)
# #
# 
# class Warrior(Character):
#     CLASS_NAME = "Warrior"
#     EMOJI      = "⚔️"
# 
#     def special_attack(self, other):
#         if self.mana >= 10:
#             damage, crit = self.crit_check(random.randint(20, 30))
#             self.mana   -= 10
#             other.health = max(0, other.health - damage)
#             msg = f"⚔️ {self.name} uses **Heavy Slash** for **{damage}** damage!"
#             return msg + " 🔥 *Critical hit!*" if crit else msg
#         return f"❌ {self.name} doesn't have enough mana for Heavy Slash!"
# 
# # =============================================================================
# # 👇 TODO 1 — Paste your CONVERTED class here
# # =============================================================================
# #
# 
# # This is the class you converted and tested in the Scratch Pad above.
# # Paste it from  "class YourName(Character):"  down to its last line.
# # Do NOT paste the Character base class — it's already defined above.
# #
# # Reminder of the four edits (all done already if the test passed):
# #
# #   1. Add these two lines right after "class YourClass(Character):"
# #          CLASS_NAME = "YourClass"     ← name shown in the dropdown
# #          EMOJI      = "🔮"            ← emoji shown next to your character
# #
# #   2. Change  print("...")  →  return f"..."  in your special_attack method
# #      (the base class methods — basic_attack, heal, meditate — are already done)
# #
# #   3. Update crit_check unpacking:
# #          OLD:  damage = self.crit_check(damage)
# #          NEW:  damage, crit = self.crit_check(damage)
# #
# # ✨ That's it!  Your class will drop right into the rest of the app.
# #
# # EXAMPLE (Mage from Day 1 adapted):
# # ─────────────────────────────────
# class Mage(Character):
#      CLASS_NAME = "Mage"
#      EMOJI      = "🔮"
# 
#      def special_attack(self, other):
#          if self.mana >= 15:
#              damage, crit = self.crit_check(random.randint(25, 35))
#              self.mana   -= 15
#              other.health = max(0, other.health - damage)
#              msg = f"🔮 {self.name} casts Fireball for **{damage}** damage!"
#              return msg + " 🔥 *Critical hit!*" if crit else msg
#          return f"❌ {self.name} doesn't have enough mana for Fireball!"
# #
# # ─────────────────────────────────
# # YOUR CLASS GOES BELOW THIS LINE:
# #
# # ⚠️ Didn't run the Conversion Test yet? Go back and do it. A class that
# #    still uses print() will look fine here and then show blank lines in
# #    the battle log, with no error message anywhere you can see it.
# 
# 
# # =============================================================================
# # 💡 Want to add something new to your game?
# # =============================================================================
# # This is your chance to expand! Ideas:
# #   • Give each class different HP or mana (change self.health in __init__)
# #   • Add a third class (Rogue, Archer, Paladin…)
# #   • Give your character a new special move
# #   • Add a passive ability (e.g. Warrior takes 10% less damage)
# # =============================================================================
# 
# # ── Boss  (given — your Day 2 AI work, already adapted) ───────────────────────
# 
# class Boss(Character):
#     CLASS_NAME = "Boss"
#     EMOJI      = "👹"
# 
#     def __init__(self):
#         super().__init__("Doom Bringer")
#         self.health = self.max_health = 150
#         self.mana   = self.max_mana   = 40
# 
#     def special_move(self, target):
#         if self.mana >= 20:
#             damage, crit = self.crit_check(random.randint(40, 50))
#             self.mana   -= 20
#             target.health = max(0, target.health - damage)
#             msg = f"💢 Doom Bringer unleashes **Desolation Wave** for **{damage}** damage!"
#             return msg + " 🔥 *Critical hit!*" if crit else msg
#         return self.basic_attack(target)
# 
#     def choose_ai_action(self, target):
#         # Attempt special move if low HP and mana allows
#         if self.health < 50 and self.mana >= 20:
#             return self.special_move(target)
#         # Priority-based action selection (your Day 2 logic!)
#         options = []
#         if self.mana >= 10 and self.health < 60:
#             options.append(("heal",     40 + (60 - self.health)))
#         if self.mana < 10:
#             options.append(("meditate", 30 - self.mana))
#         if self.mana >= 20:
#             options.append(("special",  10 + (100 - target.health)))
#         options.append(("basic",        5  + random.randint(0, 5)))
#         best = max(options, key=lambda x: x[1])[0]
#         if best == "heal":     return self.heal()
#         if best == "meditate": return self.meditate()
#         if best == "special":  return self.special_move(target)
#         return self.basic_attack(target)
# 
# # =============================================================================
# # PART 2 — STREAMLIT APP  (all given — this is the new Day 3 content!)
# # =============================================================================
# 
# def init_state():
#     defaults = {
#         "screen":  "setup",
#         "player":  None,
#         "boss":    None,
#         "log":     [],
#         "turn":    0,
#         "potions": 3,   # bonus feature — each restores 30 HP
#     }
#     for key, val in defaults.items():
#         if key not in st.session_state:
#             st.session_state[key] = val
# 
# init_state()
# state = st.session_state
# 
# def log(msg):
#     state["log"].append(msg)
#     if len(state["log"]) > 30:
#         state["log"].pop(0)
# 
# def render_setup():
#     st.title("⚔️ Boss Battle RPG")
#     st.subheader("Choose your hero to face the Doom Bringer!")
#     st.divider()
# 
#     col_left, col_right = st.columns(2)
#     with col_left:
#         name = st.text_input("Hero name", placeholder="Enter your name…")
#     with col_right:
#         # 👇 TODO 2 — Add your class name to this list
#         #    Example: ["Warrior ⚔️", "Engineer 🔮"]
#         cls = st.selectbox("Class", ["Warrior ⚔️", "Mage 🔮"])
# 
#     c1, c2 = st.columns(2)
#     with c1:
#         st.info("**Warrior ⚔️**\nHP: 100  ·  Heavy Slash (10 MP)\n_Tough melee fighter_")
#     # 👇 TODO 3 — Add a description card for your class (uncomment + fill in)
#     # with c2:
#         st.info("**Mage 🔮**\nHP: 100  ·  Fireball (15 MP)\n_ Magician")
# 
#     st.divider()
#     if st.button("⚔️  Start Battle!", type="primary", use_container_width=True):
#         if not name.strip():
#             st.warning("Please enter a hero name!")
#             return
#         if cls.startswith("Warrior"):
#             state["player"] = Warrior(name.strip())
#         # 👇 TODO 4 — Add your class here (uncomment + update YourClass)
#         elif cls.startswith("Mage"):
#              state["player"] = Mage(name.strip())
# 
#         state["boss"]    = Boss()
#         state["log"]     = ["⚔️ **Battle Start!** The Doom Bringer rises from the shadows…"]
#         state["potions"] = 3
#         state["screen"]  = "battle"
#         st.rerun()
# 
# def render_battle():
#     player = state["player"]
#     boss   = state["boss"]
# 
#     st.title("⚔️ Boss Battle")
# 
#     left, mid, right = st.columns([5, 1, 5])
#     with left:
#         st.markdown(f"## {player.EMOJI}  {player.name}")
#         st.caption(player.CLASS_NAME)
#         st.caption(f"❤️ HP  {player.health} / {player.max_health}")
#         st.progress(player.health / player.max_health)
#         st.caption(f"💎 MP  {player.mana} / {player.max_mana}")
#         st.progress(player.mana / player.max_mana)
#         st.caption(f"🧪 Potions: {state['potions']}")
#     with mid:
#         st.markdown(
#             "<div style='text-align:center;padding-top:2rem;font-size:2rem'>⚡</div>",
#             unsafe_allow_html=True)
#     with right:
#         st.markdown(f"## {boss.EMOJI}  {boss.name}")
#         st.caption(f"❤️ HP  {boss.health} / {boss.max_health}")
#         st.progress(boss.health / boss.max_health)
#         st.caption(f"💎 MP  {boss.mana} / {boss.max_mana}")
#         st.progress(boss.mana / boss.max_mana)
# 
#     st.divider()
#     st.subheader(f"🎮 {player.name}'s Turn — choose an action:")
#     b1, b2, b3, b4 = st.columns(4)
#     action = None
#     with b1:
#         if st.button("⚔️ Basic Attack",  use_container_width=True): action = "basic"
#     with b2:
#         if st.button("💥 Special Attack", use_container_width=True): action = "special"
#     with b3:
#         if st.button("💚 Heal",           use_container_width=True): action = "heal"
#     with b4:
#         if st.button(f"🧪 Potion ({state['potions']})", use_container_width=True,
#                      disabled=(state["potions"] == 0)):               action = "potion"
# 
#     if action:
#         state["turn"] += 1
#         log(f"--- **Turn {state['turn']}** ---")
# 
#         if action == "basic":
#             log(player.basic_attack(boss))
#         elif action == "special":
#             log(player.special_attack(boss))
#         elif action == "heal":
#             log(player.heal())
#         elif action == "potion":
#             state["potions"] -= 1
#             player.health = min(player.max_health, player.health + 30)
#             log(f"🧪 {player.name} drinks a potion and restores **30** HP!")
# 
#         if not boss.is_alive():
#             log(f"🏆 **{player.name} wins!** The Doom Bringer crumbles to dust!")
#             state["screen"] = "victory"
#             st.rerun()
# 
#         log(boss.choose_ai_action(player))
# 
#         if not player.is_alive():
#             log("💀 **Doom Bringer wins!** Your hero has fallen…")
#             state["screen"] = "defeat"
#             st.rerun()
# 
#         st.rerun()
# 
#     st.divider()
#     st.subheader("📜 Battle Log")
#     with st.container(height=220):
#         for entry in reversed(state["log"]):
#             st.markdown(entry)
# 
# 
# def render_victory():
#     st.balloons()
#     st.title("🏆 Victory!")
#     st.success(f"**{state['player'].name}** defeated the Doom Bringer in {state['turn']} turns!")
#     for entry in state["log"][-8:]:
#         st.markdown(entry)
#     if st.button("🔄 Play Again", type="primary"):
#         for key in ["screen", "player", "boss", "log", "turn", "potions"]:
#             del st.session_state[key]
#         st.rerun()
# 
# 
# def render_defeat():
#     st.title("💀 Game Over")
#     st.error(f"The Doom Bringer defeated **{state['player'].name}**… try again!")
#     for entry in state["log"][-8:]:
#         st.markdown(entry)
#     if st.button("🔄 Try Again", type="primary"):
#         for key in ["screen", "player", "boss", "log", "turn", "potions"]:
#             del st.session_state[key]
#         st.rerun()
# 
# 
# screens = {
#     "setup":   render_setup,
#     "battle":  render_battle,
#     "victory": render_victory,
#     "defeat":  render_defeat,
# }
# screens[state["screen"]]()
# 
# 
# # =============================================================================
# # 🎉 BONUS CHALLENGES — try these once your game is working!
# # =============================================================================
# # 1. Give each class unique starting HP/MP — add __init__ to your class and
# #    change self.health and self.mana before calling super().__init__(name)
# # 2. Add a "Meditate" button to restore mana during battle
# # 3. Add a "Flee" button that jumps straight to the defeat screen
# # 4. Add a turn limit — if the player hasn't won in 15 turns, they lose
# # 5. Add a third playable class (Rogue? Paladin? Archer?)
# # 6. Make the Boss drop loot — show a random item message on victory
# # 7. Add background music with st.audio() — find a free royalty-free MP3!
# # =============================================================================
#

"""## Cell 3 — Start the Streamlit Server

This starts the app in the background and prints the **tunnel password** you'll need in Cell 4.
"""

import subprocess, time, urllib.request

# Kill any previous Streamlit process
subprocess.run(['pkill', '-f', 'streamlit'], capture_output=True)
time.sleep(1)

# Start Streamlit in the background
subprocess.Popen(
    ['streamlit', 'run', 'app.py',
     '--server.port=8501',
     '--server.headless=true'],
    stdout=open('/content/streamlit.log', 'w'),
    stderr=subprocess.STDOUT
)

time.sleep(5)
print('✅ Streamlit is running!')

ip = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode().strip()
print(f'\n🔑 Tunnel password (copy this): {ip}')

"""## Cell 4 — Open Your Public Game URL

This cell stays **running** the whole time — that keeps the tunnel open.

1. Run the cell
2. Click the URL that appears (looks like `https://xxxxx.loca.lt`)
3. When it asks for a password, paste the IP from Cell 3
4. **Share the link with the class!**

> **To update your game:** stop this cell, re-run Cell 2 → Cell 3 → Cell 4.
"""

!npx localtunnel --port 8501

"""---
# 🎒 OPTIONAL — Give the Player an Item Bag

*Game deployed and working? Do this. Otherwise finish Part 2 first.*

Right now the player has one item: a potion, tracked by a single number (`state["potions"]`).
That works for one item. It falls apart the moment you want three.

### The data structure: a dictionary

On Day 2 you used a **list of tuples** for the boss's options. A bag is a different shape of
problem — you need to look up *"how many of THIS item do I have?"* — and that's what a
**dictionary** is for:

```python
bag = {"🧪 Potion": 3, "💎 Ether": 2, "💣 Bomb": 1}

bag["🧪 Potion"]        # → 3        look up by name
bag["🧪 Potion"] -= 1   # → 2        spend one
bag.items()             # → every (name, count) pair, for looping
```

| Structure | Shape | Good for |
|---|---|---|
| list of tuples | `[("heal", 70), ("basic", 8)]` | ranking things — Day 2's AI |
| dictionary | `{"Potion": 3, "Bomb": 1}` | looking things up by name — today's bag |

### Why this is nicer than three separate variables

With `potions`, `ethers` and `bombs` as separate numbers, adding a fourth item means editing five
places. With a dictionary, you add one line to the bag and the buttons build themselves — because
the UI code **loops over the bag** instead of naming each item.

---

## Your job: 4 edits to Cell 2

### Edit 1 — swap the potion counter for a bag

In `init_state()`, find `"potions": 3,` and replace it with:

```python
"bag": {"🧪 Potion": 3, "💎 Ether": 2, "💣 Bomb": 1},
```

### Edit 2 — write what each item does ← **this is the actual exercise**

Add this function just above `def init_state():`. One item is done for you; write the other two.

```python
def use_item(item, player, boss):
    '''Same rule as your class methods: change something, RETURN a message.'''

    if item == "🧪 Potion":
        # min() stops an overheal reporting more than it gave
        healed = min(30, player.max_health - player.health)
        player.health += healed
        return f"🧪 {player.name} drinks a Potion and restores **{healed}** HP!"

    if item == "💎 Ether":
        # TODO: restore 25 mana, capped at max_mana. Same shape as above.
        pass

    if item == "💣 Bomb":
        # TODO: deal 35-45 damage to the BOSS.
        #       Remember: boss.health = max(0, boss.health - damage)
        pass

    return "❓ Nothing happens."
```

### Edit 3 — replace the potion button with the bag row

In `render_battle()`, delete the fourth button (`b4`) and its potion block, then add this under the
other three buttons:

```python
    st.markdown("**🎒 Item Bag**")
    used_item = None
    for col, (item, count) in zip(st.columns(len(state["bag"])), state["bag"].items()):
        with col:
            if st.button(f"{item} ({count})", use_container_width=True,
                         disabled=(count == 0), key=f"item_{item}"):
                used_item = item
    if used_item:
        action = "item"
```

That `for` loop is the payoff: **add a fourth item to the bag and a fourth button appears by
itself.** You never touch this code again.

### Edit 4 — handle the action

Replace the old `elif action == "potion":` block with:

```python
        elif action == "item":
            state["bag"][used_item] -= 1
            log(use_item(used_item, player, boss))
```

And in `render_victory()` / `render_defeat()`, change `"potions"` to `"bag"` in the reset list — or
Play Again will hand you an empty bag.

---

### 🧪 Test the effects before you deploy

Paste `use_item` into the **Scratch Pad** with a fake player and boss, and call it three times. If
`min()` is missing you'll see "restores 30 HP" on a character who only gained 5.

### Going further
- An item that cures a status (needs a flag attribute — same trick as the Monk's `self.hit`)
- A shop between fights
- Make the boss drop a random item on victory: `state["bag"][item] += 1`

"""